config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    #render plain: params[:article].inspect
    @article = Article.new(article_params)

    if @article.save
      flash[:notice] = 'Article was successfully created!';
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = 'Article was successfully updated!'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def delete
    @article = Article.delete(params[:id])
  end

  def show
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<h1>Edit existing article</h1>

<% if @article.errors.any? %>
    <h3>The following erros prevent article from being created:</h3>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>

<%= form_for @article do |f| %>
    <p>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

<p><%= link_to 'Back to articles listing', articles_path %></p>

app/views/articles/index.html.erb
<h1>Listing all articles!</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>

  <% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.description %></td>
    <td><%= link_to "Edit", edit_article_path(article) %></td>
    <td><%= link_to "Read", article_path(article)%></td>
  </tr>
  <% end %>

</table>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<% if @article.errors.any? %>
    <h3>The following erros prevent article from being created:</h3>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>

<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>
  <p>
      <%= f.submit %>
  </p>
<% end %>

<p><%= link_to 'Back to articles listing', articles_path %></p>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>

<p> Title: <%= @article.title %> </p>
<p> Description: <%= @article.description %></p>

<p><%= link_to 'Back to articles listing', articles_path %></p>
<p><%= link_to 'Edit this article', edit_article_path(@article) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p><%= link_to 'Home page', root_path %></p>
  <p><%= link_to 'View articles', articles_path %></p>
  <p><%= link_to 'Create new article', new_article_path %></p>
  <p><%= link_to 'About page', about_path %></p>
    <% flash.each do |name, msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is about page</h1>

app/views/pages/home.html.erb
<h1>This is home page</h1>